### ISSUE TITLE
Duplication of "filters"

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/rfc9069-AUTH48#1]
Should "filters" be present twice in this list?

Original:
   Adj-RIB-Out received as Adj-RIB-In from another router may have a policy
   applied that filters, generates aggregates, suppresses more specific
   prefixes, manipulates attributes, or filters routes.

Perhaps:
   Adj-RIB-Out received as Adj-RIB-In from another router may have a policy
   applied that generates aggregates, suppresses more specific prefixes,
   manipulates attributes, or filters routes.

**Comment by morrowc** [comment]
This change seems appropriate to me.
