### ISSUE TITLE
Loc-RIB definition

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/rfc9069-AUTH48#2]
This text defining "Loc-RIB" is in Section 1.1 (and also appears in Section 3.2) of RFC 4271. We have updated the section number accordingly. Please let us know if there are any updates are needed.

Original:
   As defined in Section 9.4 of [RFC4271], "The Loc-RIB contains the routes                         
   that have been selected by the local BGP speaker's Decision Process."

Current:
   As defined in Section 1.1 of [RFC4271], "The Loc-RIB contains the routes                         
   that have been selected by the local BGP speaker's Decision Process."

**Comment by paololucente** [comment]
Agree & no other updates are needed on this.

**Comment by TimEvens** [comment]
> Agree & no other updates are needed on this.
+1
