### ISSUE TITLE
Loc-RIB route monitoring granularity

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/rfc9069-AUTH48#3]
For clarity, please consider whether the following update is acceptable.

Original:
   A BMP receiver should expect that Loc-RIB route monitoring granularity can
   be different by BMP sender implementation.

Perhaps:
   A BMP receiver should expect that the granularity of Loc-RIB route monitoring can
   vary depending on the BMP sender implementation.

**Comment by paololucente** [comment]
Agree

**Comment by TimEvens** [comment]
> Agree

+1
