### ISSUE TITLE
RFC 5226 reference

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/rfc9069-AUTH48#5]
There seems to be no reference to [RFC5226] in the document.  Please let us know where the citation to [RFC5226] should be placed or whether the reference should be removed.  Perhaps a citation should be added for Standards Action?

**Comment by paololucente** [comment]
I propose to remove the reference to rfc5226

**Comment by TimEvens** [comment]
This looks to have been a mistake addition via https://github.com/TimEvens/draft-ietf-grow-bmp-loc-rib/commit/83f75b4d274e5755460aef834874e6f976e9804d#diff-183973d1ddcd0bdefdc3244d6f415c940a2359e95ee38f657707b0b398e2135a.   Will remove in a PR.
