### ISSUE TITLE
Deprecation of F flag

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/rfc9069-AUTH48#7]
AD: Section 8.5 was added by version -13 of the I-D (-12 was approved); it adds the following text about deprecating an IANA value.  This matches what appears in the IANA registry.  Please verify that this update is approved.

See https://www.ietf.org/rfcdiff?url2=draft-ietf-grow-bmp-local-rib-13.

**Comment by morrowc** [comment]
@wkumari should approve this, I believe.

**Comment by wkumari** [comment]
<In the tone of a political advert> "I'm Warren Kumari, and I approve this change" </tone>
