### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/rfc9069-AUTH48#8]
Throughout the text, the following terminology appears to be used inconsistently. Please review these occurrences and let us know if/how they may be made consistent.

- Instance Peer type vs. instance peer type vs. Instance peer type

- Route Monitoring message vs. route monitoring message vs. Route Monitor message vs. route
monitor message

**Comment by paololucente** [comment]
Consistently to `rfc7854` i would propose:
- Instance Peer Type
-  Route Monitoring message

**Comment by TimEvens** [comment]
Will update both in a PR
