### ISSUE TITLE
Inclusive language

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/rfc9069-AUTH48#9]
Please review the ["Inclusive Language"](https://www.rfc-editor.org/styleguide/part2/#inclusive_language) portion of the online Style Guide.  While our script did not flag any of the potentially biased words from [Table 1](https://www.nist.gov/nist-research-library/nist-technical-series-publications-author-instructions#table1) of "NIST Technical Series Publications Author Instructions", please let us know if any changes are needed.

**Comment by paololucente** [comment]
Ack & my personal take is that there are no updates needed on this.

**Comment by TimEvens** [comment]
+1
